name: 'mdlz_transform'
version: '1.0.0'
config-version: 2

profile: 'mdlz'

vars:
  uuid_prefix: "9111215b-1f8c-4b16-9d4f-22a63b456300"
  source_bucket: "sagebackup"
  source_path: "data/parquet"
  
  # Para escritura local (no S3)
  target_local_path: "./hive_local"
  
  # Flag para control de flujo
  write_to_s3: false  # Deshabilitar escritura S3 durante pruebas

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
seed-paths: ["seeds"]

models:
  mdlz_transform:
    staging:
      +materialized: table
      +schema: staging
      +tags: ["raw", "parquet"]
    intermediate:
      +materialized: view
      +schema: intermediate
      +tags: ["intermediate"]
    marts:
      +materialized: table
      +schema: marts
      +tags: ["transformed"]
      master:
        +tags: ["master"]
      transactional:
        +tags: ["transactional"]