mdlz:
  outputs:
    dev:
      type: duckdb
      path: "./mdlz_data.db"
      threads: 4
      extensions:
        - httpfs
        - parquet
      external_root: "s3://sagebackup"  # opcional, si usas `external` en modelos
      settings:
        s3_region: "us-east-1"
        s3_endpoint: "51.79.79.6:9000"
        s3_use_ssl: false
        s3_url_style: "path"
        s3_access_key_id: "3sNmVVPCnCe8K4vsa66G"
        s3_secret_access_key: "jPc1VRq9zLKpoYHrumvYPzroXBJDai5jbg47qwwj"

  target: dev
